### ISSUE TITLE
http://s3.yedan8.com:8888/hospitalized/beds?deptId=

### ISSUE THREAD

**Issue by jwupitt** [hmlee9/yedanWiki#11]
Request Method:	GET
Request URL:	http://s3.yedan8.com:8888/hospitalized/beds?deptId=
Django Version:	1.9.4
Exception Type:	ValueError
Exception Value:	
invalid literal for int() with base 10: ''
Exception Location:	/home/yedan/workspace/ENV/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py in get_prep_value, line 976

**Comment by jwupitt** [comment]
希望能做容错处理 因为用户一些重复操作会导致这样的请求 当做是deptId没有设置

**Comment by MarvinHe** [comment]
deptId=   视为获得所有科室。
