### ISSUE TITLE
无法登记入院

### ISSUE THREAD

**Issue by jwupitt** [hmlee9/yedanWiki#16]
<img width="157" alt="screen shot 2017-02-14 at 13 51 26" src="https://cloud.githubusercontent.com/assets/4450592/22916930/b9b515ca-f2bc-11e6-945f-a9a92c06c6af.png">

**Comment by jwupitt** [comment]
<img width="169" alt="screen shot 2017-02-14 at 13 51 56" src="https://cloud.githubusercontent.com/assets/4450592/22916956/de8f1e90-f2bc-11e6-851b-145e1671806c.png">

**Comment by jwupitt** [comment]
信息应该齐全的

**Comment by MarvinHe** [comment]
之前用的 insuranceType, 现已改为 insuranceTypeId
