### ISSUE TITLE
POST http://s3.yedan8.com:8888/pricing

### ISSUE THREAD

**Issue by jwupitt** [hmlee9/yedanWiki#2]
Request Method:	POST
Request URL:	http://s3.yedan8.com:8888/pricing
Django Version:	1.9.4
Exception Type:	IOError
Exception Value:	
[Errno 5] Input/output error
Exception Location:	/usr/lib/python2.7/logging/__init__.py in callHandlers, line 1328

**Comment by jwupitt** [comment]
![wechatimg34](https://cloud.githubusercontent.com/assets/4450592/21815525/dcff7ea2-d797-11e6-9d1a-6db87f1d4e0a.jpeg)

**Comment by MarvinHe** [comment]
patient 现在所有字段都是必传， 你标记一下哪些字段为 optional 吧。
另外 insuranceType, region, sex 都应该是 int;
