### ISSUE TITLE
挂号提交，返回值需要添加打印信息，接返回值中添加了content字段

### ISSUE THREAD

**Issue by Eric124120** [hmlee9/yedanWiki#24]
挂号提交，返回值需要添加打印信息，接返回值中添加了content字段

POST /registration/submit

{
	type: '就诊类型(1-普通，2-急诊)',
	patientName: '患者姓名',
	patientSex: '患者性别（1-男，2-女）',
	patientAgeYears: '24(岁)',
	patientAgeMonths: '10(个月)',
	patientAgeDays: '20(天)'，
	doctorNum: '医生编号'
}

返回值
{
success: '0-失败，1-成功‘,
errorCode: '错误编码',
errorMsg: '错误提示信息',
"content": {
  "num": "99638882", // 门诊号
  "patient": "张三", // 患者
  "sex": "男", // 患者性别
  "receipt": "0001080701", // 发票号
  "money": "13", // 挂号费
  "moneyBig": "拾叁元", // 挂号费大写
  "date": "2017-3-2 10:30:22", // 挂号日期
  "deptName": "普通外科（就诊科室，第三科室）", // 医生科室
  "doctorName": "吴进生", // 医生名称
  "doctorLevel": "副主任医师", // 医生等级
  "seeNum": "17",  // 就诊号
  "hospital": "医院名称" // 医院名称
}
}

**Comment by bugkiwi** [comment]
@Eric124120 已经开发完成，但是`hospital`医院名称暂时没有。
