### ISSUE TITLE
密码修改失败

### ISSUE THREAD

**Issue by jwupitt** [hmlee9/yedanWiki#30]
1. 用户第一次登录后设置密码 密码没有更新

2. 设置完密码，下次登录时，isFirst应该为false了

**Comment by bugkiwi** [comment]
这个我本地测试了下，没有什么问题；
简单介绍下isFirst的逻辑，目前了解到后台，当发现密码和默认密码一样时候，就认为isFirst=True；否则就isFirst=false。

麻烦微信上给我下你对应的改密码的请求，咱俩对一下。
