### ISSUE TITLE
POST /hospitalized/

### ISSUE THREAD

**Issue by jwupitt** [hmlee9/yedanWiki#6]
POST /hospitalized/ 成功之后 拿更新后的列表 GET /hospitalized/beds出错了

**Comment by jwupitt** [comment]
![image](https://cloud.githubusercontent.com/assets/4450592/22049891/7df227f4-dd71-11e6-94e6-34ebdf60d06b.png)

**Comment by MarvinHe** [comment]
已改，之前忘记给 patient赋值了。
